### ISSUE TITLE
新增销售订单、销售出库等功能时如何添加商品呢？

### ISSUE THREAD

**Issue by githubCreate** [toesbieya/jxc-admin#11]
在使用系统演示时，销售订单、销售出库等新增功能，无法添加商品，如何操作添加商品呢，请指教。
![1](https://user-images.githubusercontent.com/30139989/101854879-60827a00-3b9d-11eb-8cb6-d08da676a400.jpg)

**Comment by toesbieya** [comment]
高阶组件的slot问题，才看到，我修一下

**Comment by toesbieya** [comment]
已修复
