### ISSUE TITLE
是否可以在销售订单和销售出库等功能新增二维码？

### ISSUE THREAD

**Issue by githubCreate** [toesbieya/jxc-admin#16]
可以在采购订单，采购入库订单，销售订单，销售出库等功能中新增二维码功能吗？扫码后可以查看订单状态，订单流程走到哪了？

**Comment by toesbieya** [comment]
不考虑增加新的业务功能，因为这个项目只是我用来学习前端的，而且这种进销存在实际业务中大概要比这个复杂100倍，所以建议要关注本项目的话只关注前端部分
