### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by rumorsy** [toesbieya/jxc-admin#18]
角色管理中的数据范围指定部门后是有什么功能？ 测试不出来

**Comment by toesbieya** [comment]
本来是想限定用户只能看指定部门数据的，后面偷懒没写，尴尬

**Comment by rumors-y** [comment]
楼主可以给个联系方式吗有个问题想私底下问问

**Comment by rumorsy** [comment]
可以指点一下部署服务器后服务连接失败的问题么

**Comment by toesbieya** [comment]
服务连接失败？底部弹出那个红色提示吗？那就是websocket没连接上，估计是websocket配置不对，[文档](https://doc.toesbieya.cn/jxc-admin/installation.html#%E5%9F%BA%E7%A1%80%E4%BF%A1%E6%81%AF%E9%85%8D%E7%BD%AE)
@rumorsy

**Comment by rumorsy** [comment]
@toesbieya 嗯嗯，不过在部署线上的时候后台设置公网ip不成功，我直接0.0.0.0才可以。 另外想请教一下，关于DOC_ID这个键值对应该如何给他设置有效期才好，发现线上部署的时候很快就失效了

**Comment by toesbieya** [comment]
DOC_ID这个有效期是永久的，ttl是-1，只有每天零点会更新一次 @rumorsy

**Comment by rumorsy** [comment]
按理来说ttl-1是永久的，可是我现在来看redis的话，DOC_ID是已经失效找不到了，不知道什么缘故 @toesbieya

**Comment by toesbieya** [comment]
那这个就不清楚了，代码里并没有对DOC_ID有删除、过期之类的操作 @rumorsy

**Comment by Floafe** [comment]
readme.md中的test/123456这个账号是系统的最高权限的账号吗？

**Comment by toesbieya** [comment]
这个是线上预览才有的测试账号，不是最高权限。
本地的默认是admin/123456 这个是最高权限（应该吧） @Floafe
