### ISSUE TITLE
请问下为什么前后端启动后前端右上角头像显示undefinedundefined（已解决）

### ISSUE THREAD

**Issue by YanHuaye1999** [toesbieya/jxc-admin#20]

**Comment by toesbieya** [comment]
试了下没问题，你是改了啥？

**Comment by q1393877285** [comment]
没动过前端代码呢，从github上面clone到本地 然后yarn install安装并运行 后端也maven下载jar构建并运行 输入账号登录后右上角就这样了 会不会package文件中依赖的版本不对





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "toesbieya/jxc-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月21日(星期天) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [toesbieya/jxc-admin] 请问下为什么前后端启动后前端右上角头像显示undefinedundefined (#20)





 
试了下没问题，你是改了啥？

**Comment by YanHuaye1999** [comment]
> 试了下没问题，你是改了啥？



> 试了下没问题，你是改了啥？

没动过前端代码呢，从github上面clone到本地 然后yarn install安装并运行 后端也maven下载jar构建并运行 输入账号登录后右上角就这样了 会不会package文件中依赖的版本不对

**Comment by toesbieya** [comment]
yarn install会不会用到package-lock.json？感觉是这个问题，换成npm试试 @q1393877285

**Comment by YanHuaye1999** [comment]
> yarn install会不会用到package-lock.json？感觉是这个问题，换成npm试试



> yarn install会不会用到package-lock.json？感觉是这个问题，换成npm试试 @q1393877285

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npm.taobao.org/@nodelib/fs.stat/-/fs.stat-1.1.3.tgz - [not_found] document not found
npm ERR! 404
npm ERR! 404  '@nodelib/fs.stat@https://registry.npm.taobao.org/@nodelib/fs.stat/-/fs.stat-1.1.3.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2021-03-21T05_27_00_987Z-debug.log

npm原版会一直卡主，切换淘宝镜像会爆上诉问题

× Install fail! Error: Unsupported URL Type: npm:vue-loader@^15.9.6
Error: Unsupported URL Type: npm:vue-loader@^15.9.6
    at parseUrl (D:\nodejs\node_global\node_modules\cnpm\node_modules\npm-package-arg\npa.js:186:13)
    at npa (D:\nodejs\node_global\node_modules\cnpm\node_modules\npm-package-arg\npa.js:79:12)
    at _install (D:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\install.js:62:11)
    at _install.next (<anonymous>)
    at onFulfilled (D:\nodejs\node_global\node_modules\cnpm\node_modules\co\index.js:65:19)
    at D:\nodejs\node_global\node_modules\cnpm\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at co (D:\nodejs\node_global\node_modules\cnpm\node_modules\co\index.js:50:10)
    at toPromise (D:\nodejs\node_global\node_modules\cnpm\node_modules\co\index.js:118:63)
    at next (D:\nodejs\node_global\node_modules\cnpm\node_modules\co\index.js:99:29)
npminstall version: 3.28.0
npminstall args: D:\nodejs\node.exe D:\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\发呆丶\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org

cnpm i会爆上面的错误。。。 真的真的能只有用yarn才能安装诶

**Comment by toesbieya** [comment]
@q1393877285 

啊这，那就只能手动固定版本了，手动修改package.json：

`"el-admin-layout": "^0.3.0"` -> `"el-admin-layout": "0.3.0"`
`"pako": "^1.0.11"` -> `"pako": "1.0.11"`

**Comment by YanHuaye1999** [comment]
> @q1393877285
> 
> 啊这，那就只能手动固定版本了，手动修改package.json：
> 
> `"el-admin-layout": "^0.3.0"` -> `"el-admin-layout": "0.3.0"`
> `"pako": "^1.0.11"` -> `"pako": "1.0.11"`

还是无法下载指定的包 能提供下您开发时的node和npm版本嘛？我这node是v14.16.0 npm是v7.6.3可能有些高了

**Comment by toesbieya** [comment]
@q1393877285 
node: v12.14.1
npm: 7.6.3

**Comment by YanHuaye1999** [comment]
> @q1393877285
> node: v12.14.1
> npm: 7.6.3

搞了一下午node和npm版本和环境，确定是npm版本问题了 npm7下某些依赖文件无法下载，我现在卸载重新安装官网node14.16.0  npm6.14.11 再npm install恢复了
