### ISSUE TITLE
请问对特定角色登录后隐藏指定的聚合菜单是那部分代码

### ISSUE THREAD

**Issue by YanHuaye1999** [toesbieya/jxc-admin#25]
修改完部门和角色数据库信息后，发现登录一般用户的账户后系统设管理显示了，原本刚刚clone到本地登录test账户是不显示“系统管理”这一菜单的

**Comment by toesbieya** [comment]
登录流程：

①登录（`@/view/_app/login/loginForm.vue #login #success`） ->

②路由拦截（`@/router/guardian/accessControl.js #beforeEach`），触发store事件->

③store初始化权限（`@/store/module/resource.js #action.init`），具体对菜单的过滤看`#getAuthorizedMenus 方法`
