### ISSUE TITLE
可不可以分离一个简易版前端

### ISSUE THREAD

**Issue by hitaoqibao** [toesbieya/jxc-admin#5]
自己尝试分离了一下，有点难分，不知作者可不可以分离出一个简易版前端模板，就登录和首页就行，保留基础布局。

**Comment by toesbieya** [comment]
如果你想不依赖后端启动的话，可以按照 [文档](https://doc.toesbieya.cn/frontend/mock.html) 来

如果是想要类似vue-element-admin-template那种的话，那需要自行精简，以后再做解耦
