### ISSUE TITLE
本地直接运行显示empty key 没有七牛云服务的路过😅

### ISSUE THREAD

**Issue by includeno** [toesbieya/jxc-admin#57]
建议弄个文件存储接口，七牛云方案只是其中一个方案，阿里云、腾讯云、亚马逊云都可以接入。没有云的可以选择本地存储

**Comment by toesbieya** [comment]
七年云我记得有每个月免费10G，够用了😇，主要当时写的时候就没考虑后续，不用文件上传的话可以try catch下`QiniuTemplate`的构造器
