### ISSUE TITLE
寻求商务合作

### ISSUE THREAD

**Issue by specialzxw** [toesbieya/jxc-admin#58]
hi，我们对您分享的这个项目十分感兴趣，如果项目已经完成的话，希望能与您进根据此项目进行课程合作，将您的技术知识分享给更多小白学习，课程制作不仅能帮助您回顾总结所学技术，还还有一定的稿费以及分成收益，如果你对我们的邀请感兴趣的话，欢迎直接联系我们的官方合作微信号 “shiyanloukecheng”，期待您的回复。

**Comment by toesbieya** [comment]
MIT，想干啥干啥
