### ISSUE TITLE
你好，请问前端和后端我都基本部署好了，可是在登录时显示登录成功但是不会跳转页面是怎么回事呢？注册用户也能加入数据库，就是不跳转页面！能帮忙看看吗？感谢！

### ISSUE THREAD

**Issue by txicecool** [toesbieya/jxc-admin#60]

**Comment by toesbieya** [comment]
应该页面报错了吧，你f12看看

**Comment by toesbieya** [comment]
你是不是改了啥，还是啥没改对，我新clone下来是没问题的

**Comment by txicecool** [comment]
f12 有一个Uncaught (in promise) ReferenceError: process is not defined报错

**Comment by txicecool** [comment]
下载下来需要改一些什么呢？

**Comment by txicecool** [comment]
显示原码if (cwd === undefined) 有错

**Comment by toesbieya** [comment]
你有改过路由配置的数据库吧？应该是有个路由路径错了，你重新导入sql试试吧

**Comment by toesbieya** [comment]
或者你试试https://github.com/browserify/path-browserify/issues/8

**Comment by txicecool** [comment]
我重新下载下来 只改了数据库密码 qiniukey 其他都没有改 运行 还是一样的问题
还需要改什么地方呢？

**Comment by toesbieya** [comment]
![20220417122741](https://user-images.githubusercontent.com/45418945/163700498-a63f49e3-84b0-4a9b-ac40-ae10a8308427.png)
你把util/path 改成这样试试

**Comment by txicecool** [comment]
可以了！谢谢
