### ISSUE TITLE
代理服务器报错 求解

### ISSUE THREAD

**Issue by XueLing-c** [toesbieya/jxc-admin#61]
错误提示如下
Proxy error: Could not proxy request /account/login from localhost:8079 to http://localhost:8081.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

**Comment by toesbieya** [comment]
后端启动了不？是8081不？唉，要学会自己找问题哇

**Comment by wsgehaishan520** [comment]
我也是这个问题，请问一下后端怎么启动呀。在src目录mvn clean package 然后构建jar吗
