### ISSUE TITLE
请问控制台报组件的错误怎么解决呢，现在演示服务器上也是一样

### ISSUE THREAD

**Issue by hanfangyu** [toesbieya/jxc-admin#62]
如图求助，谢谢
<img width="1250" alt="微信截图_20220520014411" src="https://user-images.githubusercontent.com/56426782/169364169-f0cfc9ab-d196-47cc-bbb8-4b684559c851.png">

**Comment by toesbieya** [comment]
emmm，我线上试了下是正常的，你看看点采购入库时加载的js返回的是啥，或者ctrl+f5刷新下

**Comment by hanfangyu** [comment]
但是我看线上也是显示不出来的，如下
![image](https://user-images.githubusercontent.com/56426782/169541966-d623b3bb-97f3-4f50-9621-3313bffeda1a.png)

我本地js是这样
![image](https://user-images.githubusercontent.com/56426782/169542239-41e736de-2e89-494c-a715-79dff2ed0e83.png)
![image](https://user-images.githubusercontent.com/56426782/169542328-5634737e-bf1b-417c-bd9b-0d7fc8c0fa5b.png)

不知道是路由问题还是哪里，麻烦大佬再给看看

**Comment by toesbieya** [comment]
你换chrome试试呢，这个项目只支持高版本chrome

**Comment by hanfangyu** [comment]
换chrome好了，项目用起来针不辍 (๑•̀ㅂ•́)و✧

**Comment by toesbieya** [comment]
😋😋😋
