### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by ahh556** [toesbieya/jxc-admin#64]
首先先感谢你的分享，用来改成毕设哈哈，可以节省不少时间。然后就是在走流程的过程中发现了bug具体如下：
在物品入库时有概率报错，报this.parentSubList.find is not a function。经过研究发现，this.parentSubList 的值在被赋值时有两种可能，
一种是this.parentSubList = sub，一种是return getParentSubById.request(this.form.pid).then(data => this.parentSubList = data)，其中第一种方式时sub是一个数组，其拥有find方法，但是第二种方式时由于是返回的data，它不是数组，不拥有find方法。发送概率出错的原因就在于此，因为this.parentSubList的定义是一个数组，所以用sub赋值的故不会报错，可是通过data赋值时就会报错（this.parentSubList.find is not a function），需要把第二种赋值方式修改为return getParentSubById.request(this.form.pid).then(data => this.parentSubList = data.data)即可解决。

**Comment by toesbieya** [comment]
可以啊很强，已经修复了，以前太菜了BUG一堆😋
