### ISSUE TITLE
websocket的作用？

### ISSUE THREAD

**Issue by wangmb** [toesbieya/jxc-admin#9]
我不太懂前端，有个疑问，前端增加websocket的目的是什么？能否禁用掉websocket？谢谢能答疑

**Comment by toesbieya** [comment]
本项目的websocket是为了实现统计在线用户、踢掉在线用户、实时消息、用户不可重复登陆等功能，要移除的话后端也要移除相应代码，当然如果你只是为了想使用前端的基础部分，那直接删了没什么问题
